mamNonTuongLaiTuoiSang/Models/HocSinhLop.cs
using System;
using System.Collections.Generic;

namespace mamNonTuongLaiTuoiSang.Models
{
    public partial class HocSinhLop
    {
        public HocSinhLop()
        {
            DiemDanhs = new HashSet<DiemDanh>();
        }

        public string IdHs { get; set; } = null!;
        public string IdLop { get; set; } = null!;
        public decimal? DiemChuyenCan { get; set; }

        public virtual HocSinh IdHsNavigation { get; set; } = null!;
        public virtual Lop IdLopNavigation { get; set; } = null!;
        public virtual ICollection<DiemDanh> DiemDanhs { get; set; }
    }
}

mamNonTuongLaiTuoiSang/Areas/Admin/Controllers/HocSinhLopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mamNonTuongLaiTuoiSang.Models;
using Newtonsoft.Json;
using mamNonTuongLaiTuoiSang.Areas.Admin.Models.DTO;
using System.Text;

namespace mamNonTuongLaiTuoiSang.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HocSinhLopController : Controller
    {
        private string baseURL = "http://localhost:5005/api/HocSinhLops";
        private readonly QLMamNonContext _context;
        private HttpClient client = new HttpClient();

        public HocSinhLopController(QLMamNonContext context)
        {
            _context = context;
        }

        // GET: Admin/HocSinhLop
        public async Task<IActionResult> Index(string sortOrder, string diemChuyenCanFilter)
        {
            ViewData["DiemChuyenCanSortParam"] = sortOrder == "diemchuyencan_asc" ? "diemchuyencan_desc" : "diemchuyencan_asc";
            ViewBag.DiemChuyenCanSortParm = sortOrder == "diemchuyencan_asc" ? "diemchuyencan_desc" : "diemchuyencan_asc";
            ViewBag.FilterOption = diemChuyenCanFilter;

            ViewBag.DiemChuyenCanFilterOptions = new SelectList(new[]
            {
                new { Value = "All", Text = "All" },
                new { Value = "below5", Text = "Dưới 5" },
                new { Value = "between5and8", Text = "Từ 5 đến dưới 8" },
                new { Value = "between8and10", Text = "Từ 8 đến 10" }
            }, "Value", "Text", diemChuyenCanFilter);

            List<HocSinhLop> hocSinhLops = new List<HocSinhLop>();
            HttpResponseMessage response = client.GetAsync(baseURL).Result;

            if (response.IsSuccessStatusCode)
            {
                string result = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<List<HocSinhLop>>(result);
                if (data != null)
                {
                    hocSinhLops = data;
                }
            }
            if (!string.IsNullOrEmpty(diemChuyenCanFilter) && diemChuyenCanFilter != "All")
            {
                switch (diemChuyenCanFilter)
                {
                    case "below5":
                        hocSinhLops = hocSinhLops.Where(hs => hs.DiemChuyenCan < 5).ToList();
                        break;
                    case "between5and8":
                        hocSinhLops = hocSinhLops.Where(hs => hs.DiemChuyenCan >= 5 && hs.DiemChuyenCan < 8).ToList();
                        break;
                    case "between8and10":
                        hocSinhLops = hocSinhLops.Where(hs => hs.DiemChuyenCan >= 8 && hs.DiemChuyenCan <= 10).ToList();
                        break;
                    default:
                        break;
                }
            }

            // Sắp xếp kết quả
            switch (sortOrder)
            {
                case "id_desc":
                    hocSinhLops = hocSinhLops.OrderByDescending(hs => hs.IdHs).ToList();
                    break;
                case "diemchuyencan_asc":
                    hocSinhLops = hocSinhLops.OrderBy(hs => hs.DiemChuyenCan).ToList();
                    break;
                case "diemchuyencan_desc":
                    hocSinhLops = hocSinhLops.OrderByDescending(hs => hs.DiemChuyenCan).ToList();
                    break;
                default:
                    hocSinhLops = hocSinhLops.OrderBy(hs => hs.IdHs).ToList();
                    break;
            }
        
            return View(hocSinhLops);
        }

        // GET: Admin/HocSinhLop/Details/5
        public async Task<IActionResult> Details(string id)
        {
            HocSinhLop hsl = new HocSinhLop();
            HttpResponseMessage response = client.GetAsync(baseURL + "/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                string result = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<HocSinhLop>(result);
                if (data != null)
                {
                    hsl = data;
                }
            }
            return View(hsl);
        }

        // GET: Admin/HocSinhLop/Create
        public IActionResult Create()
        {
            ViewData["IdHs"] = new SelectList(_context.HocSinhs, "IdHs", "IdHs");
            ViewData["IdLop"] = new SelectList(_context.Lops, "IdLop", "IdLop");
            return View();
        }

        // POST: Admin/HocSinhLop/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdHs,IdLop,DiemChuyenCan")] HocSinhLop hocSinhLop)
        {
            string data = JsonConvert.SerializeObject(hocSinhLop);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PostAsync(baseURL+"/", content).Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["Insert_message"] = "Add Success...";
                return RedirectToAction("Index");
            }
            ViewData["IdHs"] = new SelectList(_context.HocSinhs, "IdHs", "IdHs");
            ViewData["IdLop"] = new SelectList(_context.Lops, "IdLop", "IdLop");
            return View(hocSinhLop);
            
        }


        // GET: Admin/HocSinhLop/Edit/5
        public async Task<IActionResult> Edit(string id)
        {

            if (id == null)
            {
                return NotFound();
            }
            HocSinhLop hocSinhLop = await FindHSL(id);
            if (hocSinhLop == null)
            {
                return NotFound();
            }
            ViewData["IdHs"] = new SelectList(_context.HocSinhs, "IdHs", "IdHs", hocSinhLop.IdHs);
            ViewData["IdLop"] = new SelectList(_context.Lops, "IdLop", "IdLop", hocSinhLop.IdLop);
            return View(hocSinhLop);
        }

        // POST: Admin/HocSinhLop/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("IdHs,IdLop,DiemChuyenCan")] HocSinhLop hocSinhLop)
        {
            string data = JsonConvert.SerializeObject(hocSinhLop);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = client.PutAsync(baseURL + "/" + hocSinhLop.IdHs, content).Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["update_message"] = "Edit Success...";
                return RedirectToAction("Index");
            }
            return View(hocSinhLop);
        }


        // GET: Admin/HocSinhLop/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            HocSinhLop hsl = new HocSinhLop();
            HttpResponseMessage response = client.GetAsync(baseURL + "/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                string result = response.Content.ReadAsStringAsync().Result;
                var data = JsonConvert.DeserializeObject<HocSinhLop>(result);
                if (data != null)
                {
                    hsl = data;
                }
            }
            return View(hsl);
        }

        // POST: Admin/HocSinhLop/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            HttpResponseMessage response = client.DeleteAsync(baseURL + "/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                    TempData["delete_message"] = "Deleted...";
                    return RedirectToAction("Index");
            }
            return View();
        }
        public async Task<HocSinhLop> FindHSL(string id)
        {
            if (id == null)
            {
                return null;
            }
            using (var hocsinhlop = new HttpClient())
            {
                string path = baseURL + "/" + id;
                hocsinhlop.DefaultRequestHeaders.Accept.Clear();
                hocsinhlop.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage getData = await hocsinhlop.GetAsync(path);
                if (getData.IsSuccessStatusCode)
                {
                    var data = getData.Content.ReadAsStringAsync().Result;
                    var HocSinhLopResponse = JsonConvert.DeserializeObject<HocSinhLop>(data);
                    if (HocSinhLopResponse == null)
                    {
                        return null;
                    }
                    HocSinhLop hocSinhLop = HocSinhLopResponse;
                    return hocSinhLop;
                }
            }
            return null;
        }
        [HttpGet]
        public async Task<IActionResult> Search(string searchQuery)
        {
            if (string.IsNullOrEmpty(searchQuery))
            {
                return RedirectToAction("Index"); 
            }

            var hocSinhLop = await _context.HocSinhLops
            .FirstOrDefaultAsync(hsl => hsl.IdHs.Contains(searchQuery));

            if (hocSinhLop == null)
            {
                return NotFound(); 
            }

            return RedirectToAction("Details", new { id = hocSinhLop.IdHs });
        }
        private bool HocSinhLopExists(string id)
        {

mamNonTuongLaiTuoiSang/Controllers/HocSinhLopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mamNonTuongLaiTuoiSang.Models;

namespace mamNonTuongLaiTuoiSang.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class HocSinhLopsController : ControllerBase
    {
        private readonly QLMamNonContext _context;

        public HocSinhLopsController(QLMamNonContext context)
        {
            _context = context;
        }

        // GET: api/HocSinhLops
        [HttpGet]
        public async Task<ActionResult<IEnumerable<HocSinhLop>>> GetHocSinhLops()
        {
          if (_context.HocSinhLops == null)
          {
              return BadRequest("Dữ liệu không tồn tại.");
          }

            return await _context.HocSinhLops.ToListAsync();
        }

        // GET: api/HocSinhLops/
        [HttpGet("{idHs}")]
        public async Task<ActionResult<HocSinhLop>> GetHocSinhLop(string idHs)
        {
            if (_context.HocSinhLops == null)
            {
                return BadRequest("Dữ liệu không tồn tại.");
            }

            var hocSinhLop = await _context.HocSinhLops
                .Where(hsl => hsl.IdHs == idHs)
                .FirstOrDefaultAsync();

            if (hocSinhLop == null)
            {
                return BadRequest("Dữ liệu không tồn tại.");
            }

            return hocSinhLop;
        }
        // GET: api/HocSinhLops/lop/{idLop} ( lấy mã lớp để tìm thông tin còn hàm trên lấy mã học sinh để tìm thông tin)
        [HttpGet("lop/{idLop}")]
        public async Task<ActionResult<List<HocSinhLop>>> GetHocSinhLoplop(string idLop)
        {
            if (_context.HocSinhLops == null)
            {
                return BadRequest("Dữ liệu không tồn tại.");
            }

            var hocSinhLop = await _context.HocSinhLops
                .Where(hsl => hsl.IdLop == idLop)
                .ToListAsync();

            if (hocSinhLop == null)
            {
                return BadRequest("Dữ liệu không tồn tại.");

            }

            return hocSinhLop;
        }

        // PUT: api/HocSinhLops/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutHocSinhLop(string id, HocSinhLop hocSinhLop)
        {

            _context.Entry(hocSinhLop).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HocSinhLopExists(id))
                {
                    return BadRequest("Dữ liệu không tồn tại.");

                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/HocSinhLops
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<HocSinhLop>> PostHocSinhLop(HocSinhLop hocSinhLop)
        {
            _context.HocSinhLops.Add(hocSinhLop);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                if (HocSinhLopExists(hocSinhLop.IdHs))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return CreatedAtAction("GetHocSinhLop", new { id = hocSinhLop.IdHs }, hocSinhLop);
        }

        // DELETE: api/HocSinhLops/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteHocSinhLop(string id)
        {

            if (_context.HocSinhLops == null)
            {
                return BadRequest("Dữ liệu không tồn tại.");
            }
            var hocSinhLop = await _context.HocSinhLops.FirstOrDefaultAsync(h => h.IdHs == id);
            if (hocSinhLop == null)
            {
                return BadRequest("Dữ liệu không tồn tại.");
            }

            _context.HocSinhLops.Remove(hocSinhLop);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool HocSinhLopExists(string id)
        {
            return (_context.HocSinhLops?.Any(e => e.IdHs == id)).GetValueOrDefault();
        }
    }
}

mamNonTuongLaiTuoiSang/Areas/Admin/Views/HocSinhLop/Create.cshtml
@model mamNonTuongLaiTuoiSang.Models.HocSinhLop

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>HocSinhLop</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdHs" class="control-label"></label>
                <select asp-for="IdHs" class="form-control" asp-items="ViewBag.IdHs"></select>
                <span asp-validation-for="IdHs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdLop" class="control-label"></label>
                <select asp-for="IdLop" class="form-control" asp-items="ViewBag.IdLop"></select>
                <span asp-validation-for="IdLop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiemChuyenCan" class="control-label"></label>
                <input asp-for="DiemChuyenCan" class="form-control" type=""/>
                <span asp-validation-for="DiemChuyenCan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

mamNonTuongLaiTuoiSang/Areas/Admin/Views/HocSinhLop/Delete.cshtml
@model mamNonTuongLaiTuoiSang.Models.HocSinhLop

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HocSinhLop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiemChuyenCan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemChuyenCan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdLop)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdHs" />
        <input type="hidden" asp-for="IdLop" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

mamNonTuongLaiTuoiSang/Areas/Admin/Views/HocSinhLop/Details.cshtml
@model mamNonTuongLaiTuoiSang.Models.HocSinhLop

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>HocSinhLop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiemChuyenCan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiemChuyenCan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdLop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdLop)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

mamNonTuongLaiTuoiSang/Areas/Admin/Views/HocSinhLop/Edit.cshtml
@model mamNonTuongLaiTuoiSang.Models.HocSinhLop

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>HocSinhLop</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdHs" />
            <input type="hidden" asp-for="IdLop" />
            <div class="form-group">
                <label asp-for="DiemChuyenCan" class="control-label"></label>
                <input asp-for="DiemChuyenCan" class="form-control" />
                <span asp-validation-for="DiemChuyenCan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

mamNonTuongLaiTuoiSang/Areas/Admin/Views/HocSinhLop/Index.cshtml
@model IEnumerable<mamNonTuongLaiTuoiSang.Models.HocSinhLop>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<script>
    function redirectToCreate() {
        window.location.href = '@Url.Action("Create", "HocSinhLop", new { area = "Admin" })';
    }
</script>
<p>
    <button onclick="redirectToCreate()" class="btn btn-primary">Create New</button>
</p>
<form asp-action="Index" method="get" class="form-inline mb-3">
    <!-- Lọc theo DiemChuyenCan -->
    <div class="form-group mr-2">
        @Html.DropDownList("diemChuyenCanFilter", (SelectList)ViewBag.DiemChuyenCanFilterOptions, new { @class = "form-control", @id = "diemChuyenCanFilter" })
    </div>

    <!-- Nút Tìm và Lọc -->
    <button type="submit" class="btn btn-primary">
        <i class="fas fa-search"></i> Tìm &amp; Lọc
    </button>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DiemChuyenCanSortParam"]">
                @Html.DisplayNameFor(model => model.DiemChuyenCan)
                </a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdLop)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DiemChuyenCan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdLop)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.IdHs }) |
                    @Html.ActionLink("Details", "Details", new { id = item.IdHs }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.IdHs })
            </td>
        </tr>
}
    </tbody>
</table>